on:
    workflow_dispatch:

jobs:
    actions-job:
        runs-on: ubuntu-latest
        steps:
          - name: say Hello 
            uses: .github/actions/Greeting@v1
            with:
              name: Ahmed
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                