on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name : set API Key 
      run : echo "API_KEY=123456" >> $GITHUB_ENV
    - name : Use API Key 
      run : echo " Using API Key $API_KEY " 
    
      
