name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  example-jop:
   runs-on: ubuntu-latest

   steps:
     - name : Print a welcome message
       run: echo "Welcome to Our Github Action Test! "
