name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  example-jop:
   runs-on: ubuntu-latest

   steps:
     - name : Print a welcome message
       run: echo "Welcome to Our Github Action Test! "

     - name: Chekout repository 
       uses: actions/checkout@v6.0.2

     - name: list repoitory files
       run: ls -la 
   
